### ISSUE TITLE
能否提供关于optimization方案的参考文献呢

### ISSUE THREAD

**Issue by Rphilliplee** [wenqing-2021/AutomatedValetParking#1]
版主您好，最近也在研究HAstar相关方案，请问您当时这个repo实现方法是否有参考已有的工程或者文献，或者您是否有根据这个工程发表了相关论文可供学习，如能提供，不胜感激

**Comment by wenqing-2021** [comment]
您好！初始解的搜索就是用的hybrid Astar，然后进行路径优化，优化部分参考了阿波罗的路径优化方案。目标函数考虑路径紧凑度、平顺度、偏移度。这个开源项目只是一些个人的工程实践，没有发表论文。速度规划只是简单的用了三角函数，把轨迹作为初始解然后再进行优化求解。
